### ISSUE TITLE
Exception during install on Win11 V1.7.9

### ISSUE THREAD

**Issue by Pirotom** [ryancog/ProffieConfig#7]
When trying to install I got an exception that made the launcher crash. It couldn't create the directories and later reported an illegal character. The log file said:

ProffieConfig Launcher Log (VERSION-NOTFOUND) [Context: GLOBAL]

Started at Thu Mar 20 16:05:03 2025

[Crash Handler] (ERR) Unhandled Exception: filesystem error: cannot create directories: Invalid argument [\ProffieConfig]

The second time I got this:

[Crash Handler] (ERR) Unhandled Exception: filesystem error: Cannot convertcharacter sequence: Illegal byte sequence

The log said:
ProffieConfig Launcher Log (VERSION-NOTFOUND) [Context: GLOBAL]

Started at Thu Mar 20 16:14:42 2025

[Crash Handler] (ERR) Unhandled Exception: filesystem error: Cannot convert character sequence: Illegal byte sequenceProffieConfig Launcher Log (VERSION-NOTFOUND) [Context: GLOBAL]
Started at Fri Mar 21 08:19:32 2025

OS edition: Windows 11 Home Single Language
Version: 23H2
Spanish language

User: Tomás
The accented "a" seems to be the problem. It failed when trying to create the "C:\Users\Tomás\ProffieConfig" folder.
I tried installing on my other laptop, where the user folder name is "tomas", and it worked perfectly.

Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM	12,0 GB (11,8 GB free)
System type	Sistema operativo de 64 bits, procesador basado en x64

**Comment by ryancog** [comment]
Cool, I should be able to fix this up later today.

**Comment by ryancog** [comment]
There is a new launcher on the website and on the GitHub here (either location works).

Go ahead and try it out, it should fix this issue, but let me know if it doesn't.

**Comment by Pirotom** [comment]
I tried the new version, but the error remains. Here's the log file message

ProffieConfig Launcher Log (VERSION-NOTFOUND) [Context: GLOBAL]
Started at Tue Mar 25 07:27:01 2025

[Launcher] (INFO) Checking installation status...
[Crash Handler]  (ERR) Unhandled Exception: filesystem error: Cannot convert character sequence: Illegal byte sequence

However, this time, I didn't get the "Can't create directory" error.

**Comment by ryancog** [comment]
I've released v1.7.13, which I tested on Windows using a name with (several) special, non-ASCII characters, and everything seemed to be working fine.

Launcher v1.0.5 includes the same relevant fixes for this, and so should work for you.

Hopefully since things worked fine on my machine w/ those characters in the username, it should work fine for you, but I'll keep this issue open until you've confirmed the fix works.

**Comment by Pirotom** [comment]
It worked pristinely. The fix works like a charm.
